In [8]:
import numpy as np
np.arange(0,10,1)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [14]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [15]:
np.random.rand(5)

array([0.22180997, 0.02473759, 0.90781702, 0.18740018, 0.15609841])

In [17]:
np.random.randint(1,100,10)

array([88, 50, 43,  3, 70, 28, 59, 26, 70, 51])

In [34]:
s=np.arange(0,25)

In [43]:
slice_of_S=s[0:6]


In [45]:
slice_of_S[:]=3

In [47]:
s

array([ 3,  3,  3,  3,  3,  3,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [30]:
r.dtype

dtype('int32')

In [31]:
my_list=[1,2,3]
my_list

[1, 2, 3]

In [32]:
np.array(my_list)

array([1, 2, 3])

In [50]:
np_2d=np.array([[1,2,3],[4,5,6],[6,7,8]])

In [51]:
np_2d

array([[1, 2, 3],
       [4, 5, 6],
       [6, 7, 8]])

In [57]:
np_2d[1:,0:2]

array([[4, 5],
       [6, 7]])

In [58]:
arrs=np.arange(1,11)

In [59]:
arrs

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [60]:
bool_arr=arrs >5

In [61]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [65]:
arrs[bool_arr]

array([ 6,  7,  8,  9, 10])

In [66]:
arrs[arrs>5]

array([ 6,  7,  8,  9, 10])

In [67]:
arrs[arrs<3]

array([1, 2])

In [68]:
arr_sd=np.arange(50).reshape(5,10)

In [69]:
arr_sd


array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [70]:
arr_sd[1:4,3:6]

array([[13, 14, 15],
       [23, 24, 25],
       [33, 34, 35]])

In [71]:
shubham=np.arange(1,11)

In [72]:
shubham

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [73]:
shubham+shubham

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [74]:
shubham*shubham

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [75]:
shubham*100

array([ 100,  200,  300,  400,  500,  600,  700,  800,  900, 1000])

In [76]:
shubham

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [77]:
1/0

ZeroDivisionError: division by zero

In [78]:
np.sqrt(shubham)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766])

In [79]:
arr2d = np.zeros((10,10))

In [80]:
arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [82]:

arr_length = arr2d.shape[1]

In [83]:
arr_length

10

In [85]:
for i in range(arr_length):
    arr2d[i] = i

In [86]:
arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])